// generate_sequence.js
const fs = require('fs');
const csv = require('csv-parser');

// --- Configuration ---
const inputCsvFile = 'sequence_data.csv'; // Make sure this matches the exact name of your exported CSV file
const outputJsFile = '../sequenceData.js'; // Adjust path relative to where you run the script FROM
// --- End Configuration ---

// Define the order of your columns explicitly
const COLUMN_NAMES = [
  "time", "depth", "tiltX", "tiltY", "scale", "shapeX", "shapeY",
  "waveAmp", "waveFreq", "horizAmp", "vertAmp", "offsetX", "offsetY",
  "blurRadius", "edgeIntensity", "temporalStrength", "temporalDecay"
];

const sequence = [];
let isFirstRow = true; // Flag to skip the header row

fs.createReadStream(inputCsvFile)
  // *** KEY CHANGES HERE: headers: false, skipBOM: true, separator: ',' ***
  .pipe(csv({ headers: false, skipBOM: true, separator: ',' })) // Don't auto-detect headers, skip BOM, use comma
  .on('data', (row) => {
    if (isFirstRow) {
      isFirstRow = false; // Skip the header row
      return;
    }

    const keyframe = {};
    // Map numerical indices from the CSV row to your defined column names
    for (let i = 0; i < COLUMN_NAMES.length; i++) {
      const key = COLUMN_NAMES[i];
      const value = row[`${i}`]; // Access by numerical index (e.g., row._0, row._1)

      // Convert to number if it's a valid number, otherwise keep as string (and trim)
      keyframe[key] = isNaN(Number(value)) ? value.trim() : Number(value);
    }
    sequence.push(keyframe);
  })
  .on('end', () => {
    const jsContent = `// This file is auto-generated from ${inputCsvFile} by generate_sequence.js
// !!! DO NOT EDIT THIS FILE DIRECTLY !!!
// To modify the sequence, update the CSV file (${inputCsvFile}) and re-run the script.
// Note: This script now explicitly maps CSV columns to names and skips the first row.

const sequence = ${JSON.stringify(sequence, null, 2)};

// Easing function for interpolation (ensure this is present and accessible globally in your p5.js sketch)
// Note: Your sequenceManager is designed for linear interpolation, so this function
// might not be directly used for parameter blending in the manager, but it's included
// here for consistency if other parts of your sketch rely on it.
function easing(t) {
  // Assuming 'pow' is a global function (e.g., from p5.js math functions)
  return t < 0.5 ? 16 * t * t * t * t * t : 1 - pow(-2 * t + 2, 5) / 2;
}
`;

    fs.writeFileSync(outputJsFile, jsContent);
    console.log(`✨ Sequence successfully generated from '${inputCsvFile}' and saved to '${outputJsFile}'`);
  })
  .on('error', (error) => {
    console.error('❌ Error parsing CSV:', error.message);
    console.error('Please ensure your CSV file exists and is correctly formatted (e.g., UTF-8, comma-delimited).');
  });