// This file is auto-generated from sequence_data.csv by generate_sequence.js
// !!! DO NOT EDIT THIS FILE DIRECTLY !!!
// To modify the sequence, update the CSV file (sequence_data.csv) and re-run the script.
// Note: This script now explicitly maps CSV columns to names and skips the first row.

const sequence = [
  {
    "time": 0,
    "depth": 0,
    "tiltX": 0,
    "tiltY": 0,
    "scale": 1,
    "shapeX": 0,
    "shapeY": 0,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 3,
    "edgeIntensity": 1.9,
    "temporalStrength": 1,
    "temporalDecay": 0.6
  },
  {
    "time": 4125,
    "depth": -20,
    "tiltX": 180,
    "tiltY": 0,
    "scale": 1.5,
    "shapeX": 10,
    "shapeY": 10,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 3,
    "edgeIntensity": 1.9,
    "temporalStrength": 1,
    "temporalDecay": 0.6
  },
  {
    "time": 8250,
    "depth": -30,
    "tiltX": 360,
    "tiltY": 0,
    "scale": 2,
    "shapeX": 10,
    "shapeY": 10,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 3,
    "edgeIntensity": 1.9,
    "temporalStrength": 1,
    "temporalDecay": 0.6
  },
  {
    "time": 16500,
    "depth": 15,
    "tiltX": 720,
    "tiltY": 0,
    "scale": 1,
    "shapeX": 0,
    "shapeY": 0,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 3,
    "edgeIntensity": 1.9,
    "temporalStrength": 1,
    "temporalDecay": 0.6
  },
  {
    "time": 33000,
    "depth": 25,
    "tiltX": 900,
    "tiltY": 0,
    "scale": 1.5,
    "shapeX": 5,
    "shapeY": 5,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 3,
    "edgeIntensity": 1.9,
    "temporalStrength": 1,
    "temporalDecay": 0.6
  },
  {
    "time": 41250,
    "depth": 0,
    "tiltX": 1080,
    "tiltY": 0,
    "scale": 1,
    "shapeX": 0,
    "shapeY": 0,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 3,
    "edgeIntensity": 1.9,
    "temporalStrength": 1,
    "temporalDecay": 0.6
  }
];

// Easing function for interpolation (ensure this is present and accessible globally in your p5.js sketch)
// Note: Your sequenceManager is designed for linear interpolation, so this function
// might not be directly used for parameter blending in the manager, but it's included
// here for consistency if other parts of your sketch rely on it.
function easing(t) {
  // Assuming 'pow' is a global function (e.g., from p5.js math functions)
  return t < 0.5 ? 16 * t * t * t * t * t : 1 - pow(-2 * t + 2, 5) / 2;
}
