// This file is auto-generated from sequence_data.csv by generate_sequence.js
// !!! DO NOT EDIT THIS FILE DIRECTLY !!!
// To modify the sequence, update the CSV file (sequence_data.csv) and re-run the script.
// Note: This script now explicitly maps CSV columns to names and skips the first row.

const sequence = [
  {
    "time": 0,
    "depth": 0,
    "tiltX": 0,
    "tiltY": 0,
    "scale": 1,
    "shapeX": 0,
    "shapeY": 0,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  },
  {
    "time": 4125,
    "depth": -18,
    "tiltX": 15,
    "tiltY": 36,
    "scale": 1,
    "shapeX": 3,
    "shapeY": 0,
    "waveAmp": -7,
    "waveFreq": -1,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  },
  {
    "time": 8250,
    "depth": 23,
    "tiltX": -45,
    "tiltY": -5,
    "scale": 3,
    "shapeX": 9,
    "shapeY": -2,
    "waveAmp": -1,
    "waveFreq": 3,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  },
  {
    "time": 12375,
    "depth": 4,
    "tiltX": 3,
    "tiltY": -5,
    "scale": 3,
    "shapeX": 0,
    "shapeY": 5,
    "waveAmp": 10,
    "waveFreq": 1,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  },
  {
    "time": 16500,
    "depth": 13,
    "tiltX": 49,
    "tiltY": 3,
    "scale": 2,
    "shapeX": -5,
    "shapeY": 0,
    "waveAmp": 1,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  },
  {
    "time": 20625,
    "depth": -6,
    "tiltX": 29,
    "tiltY": -7,
    "scale": 3,
    "shapeX": -6,
    "shapeY": -8,
    "waveAmp": -4,
    "waveFreq": 2,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  },
  {
    "time": 24750,
    "depth": 0,
    "tiltX": 0,
    "tiltY": 0,
    "scale": 1,
    "shapeX": 0,
    "shapeY": 0,
    "waveAmp": 0,
    "waveFreq": 0,
    "horizAmp": 1,
    "vertAmp": 1,
    "offsetX": 0,
    "offsetY": 0,
    "blurRadius": 1.8,
    "edgeIntensity": 1,
    "temporalStrength": 0.1,
    "temporalDecay": 0.9
  }
];

// Easing function for interpolation (ensure this is present and accessible globally in your p5.js sketch)
// Note: Your sequenceManager is designed for linear interpolation, so this function
// might not be directly used for parameter blending in the manager, but it's included
// here for consistency if other parts of your sketch rely on it.
function easing(t) {
  // Assuming 'pow' is a global function (e.g., from p5.js math functions)
  return t < 0.5 ? 16 * t * t * t * t * t : 1 - pow(-2 * t + 2, 5) / 2;
}
